// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"mapps_gateway/internal/conf"
	"mapps_gateway/internal/data"
	"mapps_gateway/internal/server"
	"mapps_gateway/internal/service"

	_ "go.uber.org/automaxprocs"
)

// wireApp инициализирует приложение через Dependency Injection.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	healthService := service.NewHealthService()
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	authService := service.NewAuthService(dataData, logger)
	productService := service.NewProductService(dataData, logger)
	assetManagerService := service.NewAssetManagerService(dataData, logger)
	grpcServer := server.NewGRPCServer(confServer, healthService, authService, productService, assetManagerService, logger)
	httpServer := server.NewHTTPServer(confServer, healthService, authService, productService, assetManagerService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
