// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.0
// source: viability/health.proto

package viability

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationViabilityHealth = "/viability.Viability/Health"
const OperationViabilityReady = "/viability.Viability/Ready"

type ViabilityHTTPServer interface {
	Health(context.Context, *emptypb.Empty) (*HealthReply, error)
	Ready(context.Context, *emptypb.Empty) (*ReadinessReply, error)
}

func RegisterViabilityHTTPServer(s *http.Server, srv ViabilityHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/viability/health", _Viability_Health0_HTTP_Handler(srv))
	r.GET("/api/v1/viability/ready", _Viability_Ready0_HTTP_Handler(srv))
}

func _Viability_Health0_HTTP_Handler(srv ViabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationViabilityHealth)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Health(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HealthReply)
		return ctx.Result(200, reply)
	}
}

func _Viability_Ready0_HTTP_Handler(srv ViabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationViabilityReady)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Ready(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReadinessReply)
		return ctx.Result(200, reply)
	}
}

type ViabilityHTTPClient interface {
	Health(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *HealthReply, err error)
	Ready(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *ReadinessReply, err error)
}

type ViabilityHTTPClientImpl struct {
	cc *http.Client
}

func NewViabilityHTTPClient(client *http.Client) ViabilityHTTPClient {
	return &ViabilityHTTPClientImpl{client}
}

func (c *ViabilityHTTPClientImpl) Health(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*HealthReply, error) {
	var out HealthReply
	pattern := "/api/v1/viability/health"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationViabilityHealth))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ViabilityHTTPClientImpl) Ready(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*ReadinessReply, error) {
	var out ReadinessReply
	pattern := "/api/v1/viability/ready"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationViabilityReady))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
