// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: viability/health.proto

package viability

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion9

const (
	Viability_Health_FullMethodName = "/viability.Viability/Health"
	Viability_Ready_FullMethodName  = "/viability.Viability/Ready"
)

// ViabilityClient is the client API for Viability service.
type ViabilityClient interface {
	Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthReply, error)
	Ready(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ReadinessReply, error)
}

type viabilityClient struct {
	cc grpc.ClientConnInterface
}

func NewViabilityClient(cc grpc.ClientConnInterface) ViabilityClient {
	return &viabilityClient{cc}
}

func (c *viabilityClient) Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthReply)
	err := c.cc.Invoke(ctx, Viability_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *viabilityClient) Ready(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ReadinessReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadinessReply)
	err := c.cc.Invoke(ctx, Viability_Ready_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ViabilityServer is the server API for Viability service.
type ViabilityServer interface {
	Health(context.Context, *emptypb.Empty) (*HealthReply, error)
	Ready(context.Context, *emptypb.Empty) (*ReadinessReply, error)
	mustEmbedUnimplementedViabilityServer()
}

// UnimplementedViabilityServer must be embedded to have forward compatible implementations.
type UnimplementedViabilityServer struct{}

func (UnimplementedViabilityServer) Health(context.Context, *emptypb.Empty) (*HealthReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedViabilityServer) Ready(context.Context, *emptypb.Empty) (*ReadinessReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Ready not implemented")
}
func (UnimplementedViabilityServer) mustEmbedUnimplementedViabilityServer() {}
func (UnimplementedViabilityServer) testEmbeddedByValue()                   {}

// UnsafeViabilityServer may be embedded to opt out of forward compatibility for this service.
type UnsafeViabilityServer interface {
	mustEmbedUnimplementedViabilityServer()
}

func RegisterViabilityServer(s grpc.ServiceRegistrar, srv ViabilityServer) {
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Viability_ServiceDesc, srv)
}

func _Viability_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViabilityServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Viability_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViabilityServer).Health(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Viability_Ready_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViabilityServer).Ready(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Viability_Ready_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViabilityServer).Ready(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var Viability_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "viability.Viability",
	HandlerType: (*ViabilityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _Viability_Health_Handler,
		},
		{
			MethodName: "Ready",
			Handler:    _Viability_Ready_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "viability/health.proto",
}
