// Code generated by protoc-gen-go. DO NOT EDIT.
// Regenerate via: make api  (after setting up contracts repo in Makefile)
// source: skycontrol/viability/health.proto

package viability

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReadinessReply - ответ проверки готовности сервисов.
// TODO: регенерировать proto после создания контрактов для mApps.
// Поля 5,6,7 используются для product/asset_manager статусов (временные имена).
type ReadinessReply struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Status       string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	AuthStatus   string                 `protobuf:"bytes,2,opt,name=auth_status,json=authStatus,proto3" json:"auth_status,omitempty"`
	AuthDbStatus string                 `protobuf:"bytes,3,opt,name=auth_db_status,json=authDbStatus,proto3" json:"auth_db_status,omitempty"`
	AuthUptime   string                 `protobuf:"bytes,4,opt,name=auth_uptime,json=authUptime,proto3" json:"auth_uptime,omitempty"`
	// TODO: переименовать в product_status после регенерации proto
	ProductStatus string `protobuf:"bytes,5,opt,name=telemetry_status,json=telemetryStatus,proto3" json:"product_status,omitempty"`
	// TODO: переименовать в asset_manager_status после регенерации proto
	AssetManagerStatus string `protobuf:"bytes,6,opt,name=telemetry_db_status,json=telemetryDbStatus,proto3" json:"asset_manager_status,omitempty"`
	// TODO: удалить после регенерации proto
	Unused        string `protobuf:"bytes,7,opt,name=telemetry_uptime,json=telemetryUptime,proto3" json:"unused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadinessReply) Reset() {
	*x = ReadinessReply{}
	mi := &file_viability_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadinessReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadinessReply) ProtoMessage() {}

func (x *ReadinessReply) ProtoReflect() protoreflect.Message {
	mi := &file_viability_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*ReadinessReply) Descriptor() ([]byte, []int) {
	return file_viability_health_proto_rawDescGZIP(), []int{0}
}

func (x *ReadinessReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReadinessReply) GetAuthStatus() string {
	if x != nil {
		return x.AuthStatus
	}
	return ""
}

func (x *ReadinessReply) GetAuthDbStatus() string {
	if x != nil {
		return x.AuthDbStatus
	}
	return ""
}

func (x *ReadinessReply) GetAuthUptime() string {
	if x != nil {
		return x.AuthUptime
	}
	return ""
}

func (x *ReadinessReply) GetProductStatus() string {
	if x != nil {
		return x.ProductStatus
	}
	return ""
}

func (x *ReadinessReply) GetAssetManagerStatus() string {
	if x != nil {
		return x.AssetManagerStatus
	}
	return ""
}

type HealthReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GatewayStatus string                 `protobuf:"bytes,1,opt,name=gateway_status,json=gatewayStatus,proto3" json:"gateway_status,omitempty"`
	GatewayUptime string                 `protobuf:"bytes,2,opt,name=gateway_uptime,json=gatewayUptime,proto3" json:"gateway_uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthReply) Reset() {
	*x = HealthReply{}
	mi := &file_viability_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReply) ProtoMessage() {}

func (x *HealthReply) ProtoReflect() protoreflect.Message {
	mi := &file_viability_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*HealthReply) Descriptor() ([]byte, []int) {
	return file_viability_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthReply) GetGatewayStatus() string {
	if x != nil {
		return x.GatewayStatus
	}
	return ""
}

func (x *HealthReply) GetGatewayUptime() string {
	if x != nil {
		return x.GatewayUptime
	}
	return ""
}

var File_viability_health_proto protoreflect.FileDescriptor

// rawDesc взят из SkyControl_gateway_API (проверенный дескриптор).
// После создания mApps contracts запустите: make api
const file_viability_health_proto_rawDesc = "" +
	"\n" +
	"!skycontrol/viability/health.proto\x12\tviability\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x96\x02\n" +
	"\x0eReadinessReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vauth_status\x18\x02 \x01(\tR\n" +
	"authStatus\x12$\n" +
	"\x0eauth_db_status\x18\x03 \x01(\tR\fauthDbStatus\x12\x1f\n" +
	"\vauth_uptime\x18\x04 \x01(\tR\n" +
	"authUptime\x12)\n" +
	"\x10telemetry_status\x18\x05 \x01(\tR\x0ftelemetryStatus\x12.\n" +
	"\x13telemetry_db_status\x18\x06 \x01(\tR\x11telemetryDbStatus\x12)\n" +
	"\x10telemetry_uptime\x18\a \x01(\tR\x0ftelemetryUptime\"[\n" +
	"\vHealthReply\x12%\n" +
	"\x0egateway_status\x18\x01 \x01(\tR\rgatewayStatus\x12%\n" +
	"\x0egateway_uptime\x18\x02 \x01(\tR\rgatewayUptime2\xc4\x01\n" +
	"\tViability\x12Z\n" +
	"\x06Health\x12\x16.google.protobuf.Empty\x1a\x16.viability.HealthReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/viability/health\x12[\n" +
	"\x05Ready\x12\x16.google.protobuf.Empty\x1a\x19.viability.ReadinessReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/viability/readyB/Z-sc_gateway/api/skycontrol/viability;viabilityb\x06proto3"

var (
	file_viability_health_proto_rawDescOnce sync.Once
	file_viability_health_proto_rawDescData []byte
)

func file_viability_health_proto_rawDescGZIP() []byte {
	file_viability_health_proto_rawDescOnce.Do(func() {
		file_viability_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_viability_health_proto_rawDesc), len(file_viability_health_proto_rawDesc)))
	})
	return file_viability_health_proto_rawDescData
}

var file_viability_health_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_viability_health_proto_goTypes = []any{
	(*ReadinessReply)(nil), // 0: viability.ReadinessReply
	(*HealthReply)(nil),    // 1: viability.HealthReply
	(*emptypb.Empty)(nil),  // 2: google.protobuf.Empty
}
var file_viability_health_proto_depIdxs = []int32{
	2, // 0: viability.Viability.Health:input_type -> google.protobuf.Empty
	2, // 1: viability.Viability.Ready:input_type -> google.protobuf.Empty
	1, // 2: viability.Viability.Health:output_type -> viability.HealthReply
	0, // 3: viability.Viability.Ready:output_type -> viability.ReadinessReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_viability_health_proto_init() }
func file_viability_health_proto_init() {
	if File_viability_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_viability_health_proto_rawDesc), len(file_viability_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_viability_health_proto_goTypes,
		DependencyIndexes: file_viability_health_proto_depIdxs,
		MessageInfos:      file_viability_health_proto_msgTypes,
	}.Build()
	File_viability_health_proto = out.File
	file_viability_health_proto_goTypes = nil
	file_viability_health_proto_depIdxs = nil
}
